/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MissionId = IDL.Nat;
export const BookingId = IDL.Nat;
export const Result_1 = IDL.Variant({ 'ok' : BookingId, 'err' : IDL.Text });
export const UserId = IDL.Principal;
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const StudentProgress = IDL.Record({
  'completedMissions' : IDL.Nat,
  'badge' : IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  }),
  'totalEarnings' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Result_4 = IDL.Variant({
  'ok' : StudentProgress,
  'err' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const ServiceType = IDL.Variant({
  'homeHelp' : IDL.Null,
  'other' : IDL.Null,
  'transport' : IDL.Null,
  'shopping' : IDL.Null,
  'medical' : IDL.Null,
});
export const Mission = IDL.Record({
  'id' : MissionId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'category' : ServiceType,
  'payoutAmount' : IDL.Nat,
  'pointsReward' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'arrived' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'enRoute' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'isPriority' : IDL.Bool,
  'createdAt' : Timestamp,
  'pmrUserId' : UserId,
  'notes' : IDL.Text,
  'missionId' : IDL.Opt(MissionId),
  'locationText' : IDL.Text,
  'dateTime' : Timestamp,
  'providerId' : IDL.Opt(UserId),
});
export const UserRole = IDL.Variant({
  'pmr' : IDL.Null,
  'student' : IDL.Null,
  'driver' : IDL.Null,
});
export const StudentBadge = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'silver' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'driverLicense' : IDL.Opt(IDL.Text),
  'trustScore' : IDL.Nat,
  'pmrLabel' : IDL.Bool,
  'isAvailable' : IDL.Bool,
  'totalEarningsStudent' : IDL.Nat,
  'completedMissions' : IDL.Nat,
  'familyMembers' : IDL.Vec(UserId),
  'verifiedBadge' : IDL.Bool,
  'badge' : StudentBadge,
  'profilePhotoKey' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'totalEarningsDriver' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Result_3 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const StudentDashboard = IDL.Record({
  'activeBookings' : IDL.Vec(BookingId),
  'recentMissions' : IDL.Vec(MissionId),
  'profile' : UserProfile,
});
export const ProviderSummary = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'role' : UserRole,
  'trustScore' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'verifiedBadge' : IDL.Bool,
  'badge' : StudentBadge,
  'profilePhotoKey' : IDL.Opt(IDL.Text),
});
export const Result_2 = IDL.Variant({ 'ok' : UserId, 'err' : IDL.Text });
export const BookingRequest = IDL.Record({
  'serviceType' : ServiceType,
  'isPriority' : IDL.Bool,
  'notes' : IDL.Text,
  'locationText' : IDL.Text,
  'dateTime' : Timestamp,
});

export const idlService = IDL.Service({
  'acceptMission' : IDL.Func([MissionId], [Result_1], []),
  'addFamilyMember' : IDL.Func([UserId], [Result], []),
  'completeMission' : IDL.Func([BookingId], [Result_4], []),
  'getAvailableMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'getDriverQueue' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyProfile' : IDL.Func([], [Result_3], ['query']),
  'getMyStudentDashboard' : IDL.Func([], [StudentDashboard], ['query']),
  'getPublicProviders' : IDL.Func(
      [IDL.Variant({ 'student' : IDL.Null, 'driver' : IDL.Null }), IDL.Nat],
      [IDL.Vec(ProviderSummary)],
      ['query'],
    ),
  'registerUser' : IDL.Func([UserRole, IDL.Text, IDL.Text], [Result_2], []),
  'removeFamilyMember' : IDL.Func([UserId], [Result], []),
  'requestBooking' : IDL.Func([BookingRequest], [Result_1], []),
  'submitReview' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [Result], []),
  'subscribePremium' : IDL.Func([], [Result], []),
  'toggleDriverAvailability' : IDL.Func([IDL.Bool], [Result], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [Result], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'uploadVerificationDoc' : IDL.Func([UserRole, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MissionId = IDL.Nat;
  const BookingId = IDL.Nat;
  const Result_1 = IDL.Variant({ 'ok' : BookingId, 'err' : IDL.Text });
  const UserId = IDL.Principal;
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const StudentProgress = IDL.Record({
    'completedMissions' : IDL.Nat,
    'badge' : IDL.Variant({
      'bronze' : IDL.Null,
      'gold' : IDL.Null,
      'silver' : IDL.Null,
    }),
    'totalEarnings' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({ 'ok' : StudentProgress, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const ServiceType = IDL.Variant({
    'homeHelp' : IDL.Null,
    'other' : IDL.Null,
    'transport' : IDL.Null,
    'shopping' : IDL.Null,
    'medical' : IDL.Null,
  });
  const Mission = IDL.Record({
    'id' : MissionId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'category' : ServiceType,
    'payoutAmount' : IDL.Nat,
    'pointsReward' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'arrived' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'enRoute' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'isPriority' : IDL.Bool,
    'createdAt' : Timestamp,
    'pmrUserId' : UserId,
    'notes' : IDL.Text,
    'missionId' : IDL.Opt(MissionId),
    'locationText' : IDL.Text,
    'dateTime' : Timestamp,
    'providerId' : IDL.Opt(UserId),
  });
  const UserRole = IDL.Variant({
    'pmr' : IDL.Null,
    'student' : IDL.Null,
    'driver' : IDL.Null,
  });
  const StudentBadge = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'driverLicense' : IDL.Opt(IDL.Text),
    'trustScore' : IDL.Nat,
    'pmrLabel' : IDL.Bool,
    'isAvailable' : IDL.Bool,
    'totalEarningsStudent' : IDL.Nat,
    'completedMissions' : IDL.Nat,
    'familyMembers' : IDL.Vec(UserId),
    'verifiedBadge' : IDL.Bool,
    'badge' : StudentBadge,
    'profilePhotoKey' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'totalEarningsDriver' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Result_3 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const StudentDashboard = IDL.Record({
    'activeBookings' : IDL.Vec(BookingId),
    'recentMissions' : IDL.Vec(MissionId),
    'profile' : UserProfile,
  });
  const ProviderSummary = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'role' : UserRole,
    'trustScore' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'verifiedBadge' : IDL.Bool,
    'badge' : StudentBadge,
    'profilePhotoKey' : IDL.Opt(IDL.Text),
  });
  const Result_2 = IDL.Variant({ 'ok' : UserId, 'err' : IDL.Text });
  const BookingRequest = IDL.Record({
    'serviceType' : ServiceType,
    'isPriority' : IDL.Bool,
    'notes' : IDL.Text,
    'locationText' : IDL.Text,
    'dateTime' : Timestamp,
  });
  
  return IDL.Service({
    'acceptMission' : IDL.Func([MissionId], [Result_1], []),
    'addFamilyMember' : IDL.Func([UserId], [Result], []),
    'completeMission' : IDL.Func([BookingId], [Result_4], []),
    'getAvailableMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'getDriverQueue' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyProfile' : IDL.Func([], [Result_3], ['query']),
    'getMyStudentDashboard' : IDL.Func([], [StudentDashboard], ['query']),
    'getPublicProviders' : IDL.Func(
        [IDL.Variant({ 'student' : IDL.Null, 'driver' : IDL.Null }), IDL.Nat],
        [IDL.Vec(ProviderSummary)],
        ['query'],
      ),
    'registerUser' : IDL.Func([UserRole, IDL.Text, IDL.Text], [Result_2], []),
    'removeFamilyMember' : IDL.Func([UserId], [Result], []),
    'requestBooking' : IDL.Func([BookingRequest], [Result_1], []),
    'submitReview' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [Result], []),
    'subscribePremium' : IDL.Func([], [Result], []),
    'toggleDriverAvailability' : IDL.Func([IDL.Bool], [Result], []),
    'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [Result], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'uploadVerificationDoc' : IDL.Func([UserRole, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };