/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'isPriority' : boolean,
  'createdAt' : Timestamp,
  'pmrUserId' : UserId,
  'notes' : string,
  'missionId' : [] | [MissionId],
  'locationText' : string,
  'dateTime' : Timestamp,
  'providerId' : [] | [UserId],
}
export type BookingId = bigint;
export interface BookingRequest {
  'serviceType' : ServiceType,
  'isPriority' : boolean,
  'notes' : string,
  'locationText' : string,
  'dateTime' : Timestamp,
}
export type BookingStatus = { 'requested' : null } |
  { 'cancelled' : null } |
  { 'arrived' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'enRoute' : null };
export interface Mission {
  'id' : MissionId,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'durationMinutes' : bigint,
  'category' : ServiceType,
  'payoutAmount' : bigint,
  'pointsReward' : bigint,
}
export type MissionId = bigint;
export interface ProviderSummary {
  'id' : UserId,
  'name' : string,
  'role' : UserRole,
  'trustScore' : bigint,
  'isAvailable' : boolean,
  'verifiedBadge' : boolean,
  'badge' : StudentBadge,
  'profilePhotoKey' : [] | [string],
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : BookingId } |
  { 'err' : string };
export type Result_2 = { 'ok' : UserId } |
  { 'err' : string };
export type Result_3 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_4 = { 'ok' : StudentProgress } |
  { 'err' : string };
export type ServiceType = { 'homeHelp' : null } |
  { 'other' : null } |
  { 'transport' : null } |
  { 'shopping' : null } |
  { 'medical' : null };
export type StudentBadge = { 'bronze' : null } |
  { 'gold' : null } |
  { 'silver' : null };
export interface StudentDashboard {
  'activeBookings' : Array<BookingId>,
  'recentMissions' : Array<MissionId>,
  'profile' : UserProfile,
}
export interface StudentProgress {
  'completedMissions' : bigint,
  'badge' : { 'bronze' : null } |
    { 'gold' : null } |
    { 'silver' : null },
  'totalEarnings' : bigint,
  'points' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'isPremium' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'driverLicense' : [] | [string],
  'trustScore' : bigint,
  'pmrLabel' : boolean,
  'isAvailable' : boolean,
  'totalEarningsStudent' : bigint,
  'completedMissions' : bigint,
  'familyMembers' : Array<UserId>,
  'verifiedBadge' : boolean,
  'badge' : StudentBadge,
  'profilePhotoKey' : [] | [string],
  'phone' : string,
  'totalEarningsDriver' : bigint,
  'points' : bigint,
}
export type UserRole = { 'pmr' : null } |
  { 'student' : null } |
  { 'driver' : null };
export interface _SERVICE {
  'acceptMission' : ActorMethod<[MissionId], Result_1>,
  'addFamilyMember' : ActorMethod<[UserId], Result>,
  'completeMission' : ActorMethod<[BookingId], Result_4>,
  'getAvailableMissions' : ActorMethod<[], Array<Mission>>,
  'getDriverQueue' : ActorMethod<[], Array<Booking>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyProfile' : ActorMethod<[], Result_3>,
  'getMyStudentDashboard' : ActorMethod<[], StudentDashboard>,
  'getPublicProviders' : ActorMethod<
    [{ 'student' : null } | { 'driver' : null }, bigint],
    Array<ProviderSummary>
  >,
  'registerUser' : ActorMethod<[UserRole, string, string], Result_2>,
  'removeFamilyMember' : ActorMethod<[UserId], Result>,
  'requestBooking' : ActorMethod<[BookingRequest], Result_1>,
  'submitReview' : ActorMethod<[BookingId, bigint, string], Result>,
  'subscribePremium' : ActorMethod<[], Result>,
  'toggleDriverAvailability' : ActorMethod<[boolean], Result>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], Result>,
  'updateProfile' : ActorMethod<[string, string, [] | [string]], Result>,
  'uploadVerificationDoc' : ActorMethod<[UserRole, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];