/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Mission {
    id: MissionId;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    durationMinutes: bigint;
    category: ServiceType;
    payoutAmount: bigint;
    pointsReward: bigint;
}
export type BookingId = bigint;
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: UserId;
} | {
    __kind__: "err";
    err: string;
};
export interface ProviderSummary {
    id: UserId;
    name: string;
    role: UserRole;
    trustScore: bigint;
    isAvailable: boolean;
    verifiedBadge: boolean;
    badge: StudentBadge;
    profilePhotoKey?: string;
}
export interface BookingRequest {
    serviceType: ServiceType;
    isPriority: boolean;
    notes: string;
    locationText: string;
    dateTime: Timestamp;
}
export interface StudentDashboard {
    activeBookings: Array<BookingId>;
    recentMissions: Array<MissionId>;
    profile: UserProfile;
}
export type Result_1 = {
    __kind__: "ok";
    ok: BookingId;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: StudentProgress;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface StudentProgress {
    completedMissions: bigint;
    badge: Variant_bronze_gold_silver;
    totalEarnings: bigint;
    points: bigint;
}
export interface Booking {
    id: BookingId;
    status: BookingStatus;
    serviceType: ServiceType;
    isPriority: boolean;
    createdAt: Timestamp;
    pmrUserId: UserId;
    notes: string;
    missionId?: MissionId;
    locationText: string;
    dateTime: Timestamp;
    providerId?: UserId;
}
export type MissionId = bigint;
export interface UserProfile {
    id: UserId;
    isPremium: boolean;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    driverLicense?: string;
    trustScore: bigint;
    pmrLabel: boolean;
    isAvailable: boolean;
    totalEarningsStudent: bigint;
    completedMissions: bigint;
    familyMembers: Array<UserId>;
    verifiedBadge: boolean;
    badge: StudentBadge;
    profilePhotoKey?: string;
    phone: string;
    totalEarningsDriver: bigint;
    points: bigint;
}
export enum BookingStatus {
    requested = "requested",
    cancelled = "cancelled",
    arrived = "arrived",
    completed = "completed",
    confirmed = "confirmed",
    enRoute = "enRoute"
}
export enum ServiceType {
    homeHelp = "homeHelp",
    other = "other",
    transport = "transport",
    shopping = "shopping",
    medical = "medical"
}
export enum UserRole {
    pmr = "pmr",
    student = "student",
    driver = "driver"
}
export enum Variant_bronze_gold_silver {
    bronze = "bronze",
    gold = "gold",
    silver = "silver"
}
export enum Variant_student_driver {
    student = "student",
    driver = "driver"
}
export interface backendInterface {
    acceptMission(missionId: MissionId): Promise<Result_1>;
    addFamilyMember(member: UserId): Promise<Result>;
    completeMission(bookingId: BookingId): Promise<Result_4>;
    getAvailableMissions(): Promise<Array<Mission>>;
    getDriverQueue(): Promise<Array<Booking>>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyProfile(): Promise<Result_3>;
    getMyStudentDashboard(): Promise<StudentDashboard>;
    getPublicProviders(serviceType: Variant_student_driver, minRating: bigint): Promise<Array<ProviderSummary>>;
    registerUser(role: UserRole, name: string, phone: string): Promise<Result_2>;
    removeFamilyMember(member: UserId): Promise<Result>;
    requestBooking(req: BookingRequest): Promise<Result_1>;
    submitReview(bookingId: BookingId, stars: bigint, text: string): Promise<Result>;
    subscribePremium(): Promise<Result>;
    toggleDriverAvailability(isAvailable: boolean): Promise<Result>;
    updateBookingStatus(bookingId: BookingId, newStatus: BookingStatus): Promise<Result>;
    updateProfile(name: string, phone: string, profilePhotoKey: string | null): Promise<Result>;
    uploadVerificationDoc(role: UserRole, assetKey: string): Promise<Result>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, Mission as _Mission, MissionId as _MissionId, ProviderSummary as _ProviderSummary, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, ServiceType as _ServiceType, StudentBadge as _StudentBadge, StudentDashboard as _StudentDashboard, StudentProgress as _StudentProgress, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptMission(arg0: MissionId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptMission(arg0);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptMission(arg0);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFamilyMember(arg0: UserId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addFamilyMember(arg0);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFamilyMember(arg0);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeMission(arg0: BookingId): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMission(arg0);
                return from_candid_Result_4_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMission(arg0);
            return from_candid_Result_4_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableMissions(): Promise<Array<Mission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableMissions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableMissions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverQueue(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverQueue();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverQueue();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_Result_3_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_Result_3_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStudentDashboard(): Promise<StudentDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStudentDashboard();
                return from_candid_StudentDashboard_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStudentDashboard();
            return from_candid_StudentDashboard_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProviders(arg0: Variant_student_driver, arg1: bigint): Promise<Array<ProviderSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProviders(to_candid_variant_n32(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProviders(to_candid_variant_n32(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: UserRole, arg1: string, arg2: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_Result_2_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_Result_2_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFamilyMember(arg0: UserId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFamilyMember(arg0);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFamilyMember(arg0);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestBooking(arg0: BookingRequest): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.requestBooking(to_candid_BookingRequest_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestBooking(to_candid_BookingRequest_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReview(arg0: BookingId, arg1: bigint, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async subscribePremium(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribePremium();
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribePremium();
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleDriverAvailability(arg0: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDriverAvailability(arg0);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDriverAvailability(arg0);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingStatus(arg0: BookingId, arg1: BookingStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadVerificationDoc(arg0: UserRole, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVerificationDoc(to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVerificationDoc(to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Mission_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mission): Mission {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderSummary_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderSummary): ProviderSummary {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_StudentBadge_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentBadge): StudentBadge {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_StudentDashboard_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentDashboard): StudentDashboard {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProgress_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProgress): StudentProgress {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MissionId]): MissionId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MissionId;
    createdAt: _Timestamp;
    description: string;
    isActive: boolean;
    durationMinutes: bigint;
    category: _ServiceType;
    payoutAmount: bigint;
    pointsReward: bigint;
}): {
    id: MissionId;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    durationMinutes: bigint;
    category: ServiceType;
    payoutAmount: bigint;
    pointsReward: bigint;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        durationMinutes: value.durationMinutes,
        category: from_candid_ServiceType_n13(_uploadFile, _downloadFile, value.category),
        payoutAmount: value.payoutAmount,
        pointsReward: value.pointsReward
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    serviceType: _ServiceType;
    isPriority: boolean;
    createdAt: _Timestamp;
    pmrUserId: _UserId;
    notes: string;
    missionId: [] | [_MissionId];
    locationText: string;
    dateTime: _Timestamp;
    providerId: [] | [_UserId];
}): {
    id: BookingId;
    status: BookingStatus;
    serviceType: ServiceType;
    isPriority: boolean;
    createdAt: Timestamp;
    pmrUserId: UserId;
    notes: string;
    missionId?: MissionId;
    locationText: string;
    dateTime: Timestamp;
    providerId?: UserId;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n18(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n13(_uploadFile, _downloadFile, value.serviceType),
        isPriority: value.isPriority,
        createdAt: value.createdAt,
        pmrUserId: value.pmrUserId,
        notes: value.notes,
        missionId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.missionId)),
        locationText: value.locationText,
        dateTime: value.dateTime,
        providerId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.providerId))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    isPremium: boolean;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    driverLicense: [] | [string];
    trustScore: bigint;
    pmrLabel: boolean;
    isAvailable: boolean;
    totalEarningsStudent: bigint;
    completedMissions: bigint;
    familyMembers: Array<_UserId>;
    verifiedBadge: boolean;
    badge: _StudentBadge;
    profilePhotoKey: [] | [string];
    phone: string;
    totalEarningsDriver: bigint;
    points: bigint;
}): {
    id: UserId;
    isPremium: boolean;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    driverLicense?: string;
    trustScore: bigint;
    pmrLabel: boolean;
    isAvailable: boolean;
    totalEarningsStudent: bigint;
    completedMissions: bigint;
    familyMembers: Array<UserId>;
    verifiedBadge: boolean;
    badge: StudentBadge;
    profilePhotoKey?: string;
    phone: string;
    totalEarningsDriver: bigint;
    points: bigint;
} {
    return {
        id: value.id,
        isPremium: value.isPremium,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        driverLicense: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.driverLicense)),
        trustScore: value.trustScore,
        pmrLabel: value.pmrLabel,
        isAvailable: value.isAvailable,
        totalEarningsStudent: value.totalEarningsStudent,
        completedMissions: value.completedMissions,
        familyMembers: value.familyMembers,
        verifiedBadge: value.verifiedBadge,
        badge: from_candid_StudentBadge_n29(_uploadFile, _downloadFile, value.badge),
        profilePhotoKey: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.profilePhotoKey)),
        phone: value.phone,
        totalEarningsDriver: value.totalEarningsDriver,
        points: value.points
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeBookings: Array<_BookingId>;
    recentMissions: Array<_MissionId>;
    profile: _UserProfile;
}): {
    activeBookings: Array<BookingId>;
    recentMissions: Array<MissionId>;
    profile: UserProfile;
} {
    return {
        activeBookings: value.activeBookings,
        recentMissions: value.recentMissions,
        profile: from_candid_UserProfile_n24(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    role: _UserRole;
    trustScore: bigint;
    isAvailable: boolean;
    verifiedBadge: boolean;
    badge: _StudentBadge;
    profilePhotoKey: [] | [string];
}): {
    id: UserId;
    name: string;
    role: UserRole;
    trustScore: bigint;
    isAvailable: boolean;
    verifiedBadge: boolean;
    badge: StudentBadge;
    profilePhotoKey?: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        trustScore: value.trustScore,
        isAvailable: value.isAvailable,
        verifiedBadge: value.verifiedBadge,
        badge: from_candid_StudentBadge_n29(_uploadFile, _downloadFile, value.badge),
        profilePhotoKey: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.profilePhotoKey))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedMissions: bigint;
    badge: {
        bronze: null;
    } | {
        gold: null;
    } | {
        silver: null;
    };
    totalEarnings: bigint;
    points: bigint;
}): {
    completedMissions: bigint;
    badge: Variant_bronze_gold_silver;
    totalEarnings: bigint;
    points: bigint;
} {
    return {
        completedMissions: value.completedMissions,
        badge: from_candid_variant_n9(_uploadFile, _downloadFile, value.badge),
        totalEarnings: value.totalEarnings,
        points: value.points
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    homeHelp: null;
} | {
    other: null;
} | {
    transport: null;
} | {
    shopping: null;
} | {
    medical: null;
}): ServiceType {
    return "homeHelp" in value ? ServiceType.homeHelp : "other" in value ? ServiceType.other : "transport" in value ? ServiceType.transport : "shopping" in value ? ServiceType.shopping : "medical" in value ? ServiceType.medical : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    cancelled: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    enRoute: null;
}): BookingStatus {
    return "requested" in value ? BookingStatus.requested : "cancelled" in value ? BookingStatus.cancelled : "arrived" in value ? BookingStatus.arrived : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : "enRoute" in value ? BookingStatus.enRoute : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BookingId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BookingId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pmr: null;
} | {
    student: null;
} | {
    driver: null;
}): UserRole {
    return "pmr" in value ? UserRole.pmr : "student" in value ? UserRole.student : "driver" in value ? UserRole.driver : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StudentProgress;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StudentProgress;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StudentProgress_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    silver: null;
}): Variant_bronze_gold_silver {
    return "bronze" in value ? Variant_bronze_gold_silver.bronze : "gold" in value ? Variant_bronze_gold_silver.gold : "silver" in value ? Variant_bronze_gold_silver.silver : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Mission>): Array<Mission> {
    return value.map((x)=>from_candid_Mission_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderSummary>): Array<ProviderSummary> {
    return value.map((x)=>from_candid_ProviderSummary_n34(_uploadFile, _downloadFile, x));
}
function to_candid_BookingRequest_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequest): _BookingRequest {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: ServiceType;
    isPriority: boolean;
    notes: string;
    locationText: string;
    dateTime: Timestamp;
}): {
    serviceType: _ServiceType;
    isPriority: boolean;
    notes: string;
    locationText: string;
    dateTime: _Timestamp;
} {
    return {
        serviceType: to_candid_ServiceType_n42(_uploadFile, _downloadFile, value.serviceType),
        isPriority: value.isPriority,
        notes: value.notes,
        locationText: value.locationText,
        dateTime: value.dateTime
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_student_driver): {
    student: null;
} | {
    driver: null;
} {
    return value == Variant_student_driver.student ? {
        student: null
    } : value == Variant_student_driver.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    pmr: null;
} | {
    student: null;
} | {
    driver: null;
} {
    return value == UserRole.pmr ? {
        pmr: null
    } : value == UserRole.student ? {
        student: null
    } : value == UserRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    homeHelp: null;
} | {
    other: null;
} | {
    transport: null;
} | {
    shopping: null;
} | {
    medical: null;
} {
    return value == ServiceType.homeHelp ? {
        homeHelp: null
    } : value == ServiceType.other ? {
        other: null
    } : value == ServiceType.transport ? {
        transport: null
    } : value == ServiceType.shopping ? {
        shopping: null
    } : value == ServiceType.medical ? {
        medical: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    requested: null;
} | {
    cancelled: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    enRoute: null;
} {
    return value == BookingStatus.requested ? {
        requested: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.arrived ? {
        arrived: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.enRoute ? {
        enRoute: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
